language: scala
scala:
  - 2.12.8
jdk:
  - openjdk12

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt assembly

notifications:
  email:
    - flatmap-squad@spotify.com

deploy:
  provider: releases
  api_key:
    secure: GCJ6letemyqzVPZG6fvi+ndRTDyQffWK67B3MmzhyiMgFhFzCk65GtJWqRHTGrlq87/fC2ZemUMbULpUwdSsqPtoTXdC+LMetnG2Zg7wHPbSqrplP4DrcROVmvtGf0+h5UvMc/hmHLeItsEwfHi2j7nXY+iExpHXXd1SINu6bnqOHTnHNvOUhMAwRJvDDWPFiA2ZTgycJ6rChDyMMm34yt/tDXszgM05XyWln86O8bLmo+o9mPohFVbpEZG/xITd0bEYF1yJ2OFRlj7nfrr2BWFeBOslfv3CPkSW6K2ertyjLM0as8rCH8QqR6LbhsZNF5/GmTfd1rqlWhlT5tZuElxyhaRYCtXPLyc9WfL9Il8pziQQuk0Uynw6/PVj3lq6H8mPxGz3qIf84AE2rQVqaUAcKdaE9JFWkRQXGQuPd3NcH6l6ry/H9Rapi37AzLf8P51wJrBo78fvaTu2l7W7v9zu7XgJ0Kybw5RfneudI+DAapmlBUuikprbOTgqhNt6Q5VIDtxZ4XcL63hU0xCAx6jOlioibJB+TCLKbGfUKypT/QfCTb1JbDG3AhddDDyFJCBIyf14czdHoIYKy51RBGF9IPV25nQDi+vyxQS9fpbl92zPS0TrlxBvR/+S67dUo39SIUAh57mK5h1y6yUHpvFTaKKu1ZJ+YpegEOt0zNM=
  file_glob: true
  file:
    - "avro-tools/target/scala-*/avro-tools-*.jar"
    - "parquet-tools/target/scala-*/parquet-tools-*.jar"
    - "proto-tools/target/scala-*/proto-tools-*.jar"
  skip_cleanup: true
  on:
    scala: 2.12.8
    tags: true
